routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('threads', 'ThreadController@index')->name('threads.index');
Route::post('threads', 'ThreadController@store')->name('threads.store');

Route::get('threads/create', 'ThreadController@create')->name('threads.create');

Route::get('threads/{channel}/{thread}', 'ThreadController@show')->name('threads.show');
Route::delete('threads/{channel}/{thread}', 'ThreadController@destroy')->name('threads.destroy');

Route::post('threads/{channel}/{thread}/replies', 'ReplyController@store');
Route::get('threads/{channel}', 'ThreadController@index');

Route::post('replies/{reply}/favourites', 'FavouriteController@store')->name('favourite.store');

Route::get('profiles/{user}', 'ProfileController@show')->name('profile.show');

app/Thread.php
<?php

namespace App;

use App\Traits\RecordsActivity;
use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    use RecordsActivity;

    protected $guarded = [];
    protected $with = ['owner', 'channel'];

    public static function boot()
    {
        parent::boot();

        static::addGlobalScope('replyCount', function ($builder) {
            $builder->withCount('replies');
        });

        static::deleting(function($thread) {
            $thread->replies->each->delete();
        });
    }

    public function path()
    {
        return "/threads/{$this->channel->slug}/{$this->id}";
    }

    /// Relationships

    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /// Helper

    public function addReply($reply)
    {
        $this->replies()->create($reply);
    }

    public function scopeFilter($query, $filters)
    {
        return $filters->apply($query);
    }
}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use App\Channel;
use App\Filters\ThreadFilters;
use App\Thread;
use App\User;
use Illuminate\Http\Request;

class ThreadController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @param Channel $channel
     * @param ThreadFilters $filters
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, Channel $channel, ThreadFilters $filters)
    {
        $threads = Thread::latest()->filter($filters);

        if ( $channel->exists ) {
            $threads->whereChannelId($channel->id);
        }

        $threads = $threads->get();

        if ( $request->wantsJson() )
            return $threads;

        return view('threads.index', compact('threads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('threads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'body' => 'required',
            'channel_id' => 'required|exists:channels,id',
        ]);

        $thread = Thread::create([
           'user_id' => \Auth::id(),
           'channel_id' => $request->channel_id,
           'title' => $request->title,
           'body' => $request->body,
        ]);

        $channel = Channel::find($request->channel_id);

        return redirect()->route('threads.show', ['channel' => $channel->slug, 'thread' => $thread->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param $channelId
     * @param  Thread $thread
     * @return \Illuminate\Http\Response
     */
    public function show($channelId, Thread $thread)
    {
        $replies = $thread->replies()->paginate();

        return view('threads.show', compact('thread', 'replies'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Thread $thread
     * @return void
     */
    public function edit(Thread $thread)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Thread $thread
     * @return void
     */
    public function update(Request $request, Thread $thread)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $channel
     * @param  \App\Thread $thread
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function destroy($channel, Thread $thread)
    {
        $this->authorize('delete', $thread);

        $thread->delete();

        return redirect()->route('threads.index');
    }
}

resources/views/threads/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create New Thread</div>

                    <div class="card-body">
                        <form method="post" action="{{ route('threads.store') }}">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <select name="channel_id" class="form-control" required>
                                    <option value="">..Choose a channel</option>

                                    @foreach($channels as $channel)
                                        <option value="{{ $channel->id }}" {{ old('channel_id') == $channel->id ? 'selected' : '' }}>
                                            {{ $channel->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <input class="form-control" name="title" placeholder="Add Title" value="{{ old('title') }}" required/>
                            </div>

                            <div class="form-group">
                                <textarea name="body" class="form-control" placeholder="Add Body" rows="5" required>{{ old('body') }}</textarea>
                            </div>

                            <button type="submit" class="btn btn-outline-primary">Post</button>

                            @if ( count($errors) )
                                <ul class="alert alert-danger mt-3">
                                    @foreach($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            @endif
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">All Threads <a href="{{ route('threads.create') }}">Create New Thread</a> </div>

                    <div class="card-body">
                        @foreach($threads as $thread)
                              <article>
                                  <div class="level">
                                    <h3 class="flex"><a href="{{ $thread->path() }}">{{ $thread->title }}</a></h3>
                                    <a href="{{ $thread->path() }}">{{ $thread->replies_count }} {{ str_plural('reply', $thread->replies_count) }}</a>
                                  </div>
                                  <div class="body">{{ $thread->body }}</div>
                                  <hr/>
                              </article>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/threads/reply.blade.php
<div class="card mt-4">
    <div class="card-header">
        <div class="level">
            <div class="flex">
                <a href="{{ route('profile.show', $reply->owner) }}">{{ $reply->owner->name }}</a> said {{ $reply->created_at->diffForHumans() }}
            </div>

            <div>
                <form method="post" action="{{ route('favourite.store', ['id' => $reply->id]) }}">
                    {{ csrf_field() }}
                    <button class="btn btn-outline-secondary" type="submit" name="Favourite" {{ $reply->isFavourited() ? 'disabled' : '' }}>
                        {{ $reply->favourites_count }} {{ str_plural('Favourite', $reply->favourites_count) }}
                    </button>
                </form>
            </div>
        </div>
    </div>

    <div class="card-body">
        {{ $reply->body }}
    </div>
</div>

resources/views/threads/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-md-start">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header level">
                        <span class="flex">
                            <a href="{{ route('profile.show',  $thread->owner) }}">{{ $thread->owner->name }}</a> posted: {{ $thread->title }}
                        </span>

                        @can('delete', $thread)
                        <span>
                            <form method="post" action="{{ $thread->path() }}">
                                @csrf
                                @method('delete')

                                <button class="btn btn-outline-danger" name="delete">Delete</button>
                            </form>
                        </span>
                        @endcan
                    </div>

                    <div class="card-body">
                        {{ $thread->body }}
                    </div>
                </div>

                @foreach($replies as $reply)
                    @include('threads.reply')
                @endforeach

                {{ $replies->links() }}

                @if(auth()->check())
                    <form class="mt-4" method="post" action="{{ $thread->path() . '/replies' }}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <textarea name="body" class="form-control" placeholder="Something to add...?" rows="5"></textarea>
                        </div>

                        <button type="submit" class="btn btn-outline-primary">Post</button>
                    </form>
                @endif
            </div>

            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        Useful Info
                    </div>

                    <div class="card-body">
                        <p>
                            This thread was published {{ $thread->created_at->diffForHumans() }} by
                            <a href="#">{{ $thread->owner->name }}</a> and currently has {{ $thread->replies_count }} {{ str_plural('reply', $thread->replies_count) }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection